services:
  main:
    platform: linux/amd64
    image: ghcr.io/uva-software-analysis/cs6888-public:latest
    # build: .  # Uncomment to build locally instead of using pre-built image
    command: tail -f /dev/null
    volumes: 
      - ./files:/root/files/
    environment:
      - PATH=/root/infer/bin:/root/cppcheck/build/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - DISPLAY=novnc:0.0
    networks:
      - x11
    hostname: uvacs
networks:
  x11:
